export enum PermissionTypes {
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  READ_USER_DETAILS = 'READ_USER_DETAILS',
  UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  READ_PRODUCT = 'READ_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  CREATE_PURCHASE = 'CREATE_PURCHASE',
  READ_PURCHASE = 'READ_PURCHASE',
  UPDATE_PURCHASE = 'UPDATE_PURCHASE',
  DELETE_PURCHASE = 'DELETE_PURCHASE',
  CREATE_INVOICE = 'CREATE_INVOICE',
  READ_INVOICE = 'READ_INVOICE',
  UPDATE_INVOICE = 'UPDATE_INVOICE',
  DELETE_INVOICE = 'DELETE_INVOICE',
  CREATE_BUDGET = 'CREATE_BUDGET',
  READ_BUDGET = 'READ_BUDGET',
  UPDATE_BUDGET = 'UPDATE_BUDGET',
  DELETE_BUDGET = 'DELETE_BUDGET',
  READ_ADMIN_PANEL = 'READ_ADMIN_PANEL',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  VIEW_REPORTS = 'VIEW_REPORTS',
  EXPORT_DATA = 'EXPORT_DATA',
  ASSIGN_ROLE = 'ASSIGN_ROLE',
  VIEW_ACTIVITY_LOG = 'VIEW_ACTIVITY_LOG',
  ALL_PERMISSION = 'ALL_PERMISSION',
}

export interface Permission {
  id: string
  name: PermissionTypes
  description?: string
}

export interface UserPermissions {
  userId: string
  permissions: PermissionTypes[]
}
